apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodongo
        image: 127.0.0.1:5000/reactareebk:1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
