apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: nodongo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32002
